version: 2
jobs:
  build:
    working_directory: ~/minimed-connect-to-nightscout
    docker:
      - image: circleci/node:8.11.3
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@5'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: npm-install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: run-tests
          command: npm test
